# Generated by Django 5.1.8 on 2026-04-07 06:45

import core.fields
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', core.fields.EncryptedCharField(help_text='Monto en COP. Encriptado AES-256.', max_length=512)),
                ('referencia_bancaria', models.CharField(db_index=True, help_text='Referencia única del comprobante. Usada para deduplicación.', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('transferencia_propia', 'Transferencia entre cuentas propias')], default='gasto', max_length=25)),
                ('entidad', models.CharField(choices=[('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('bancolombia', 'Bancolombia'), ('otro', 'Otro')], max_length=20)),
                ('categoria', models.CharField(blank=True, default='sin_categorizar', help_text='Categoría inferida por IA o asignada por usuario', max_length=50)),
                ('destinatario', models.CharField(blank=True, help_text='Nombre del receptor/emisor del pago', max_length=200)),
                ('fecha_transaccion', models.DateTimeField(help_text='Fecha/hora de la transacción según el comprobante')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción extraída o nota del usuario')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmada por usuario'), ('rejected', 'Rechazada por usuario'), ('needs_review', 'Requiere revisión manual'), ('error', 'Error en procesamiento')], default='pending', max_length=20)),
                ('confianza_ia', models.FloatField(default=0.0, help_text='Nivel de confianza de la extracción IA (0.0 a 1.0)')),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='ID del mensaje de WhatsApp original', max_length=100, null=True)),
                ('raw_gemini_response', models.JSONField(blank=True, help_text='Respuesta cruda de Gemini para debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions_transaction',
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='TransactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen original del comprobante', upload_to=transactions.models.comprobante_upload_path)),
                ('content_type', models.CharField(default='image/jpeg', max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Tamaño en bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions_image',
            },
        ),
    ]
