# Generated by Django 5.1.15 on 2026-04-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', help_text='Plan del usuario: free (limitado) o premium (ilimitado + WhatsApp)', max_length=10),
        ),
    ]
